<?php
defined('BASEPATH') OR exit('No direct script access allowed');
?>
<!DOCTYPE html>
<html lang="en">
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Careerism</title>
<!-- Bootstrap -->
<link href="<?php echo base_url(); ?>assets/template/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="<?php echo base_url(); ?>assets/template/css/font-awesome.min.css">
<link rel="stylesheet" href="<?php echo base_url(); ?>assets/template/css/animate.css">
<link href="<?php echo base_url(); ?>assets/template/css/prettyPhoto.css" rel="stylesheet">
<link href="<?php echo base_url(); ?>assets/template/css/style.css" rel="stylesheet">	
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<style>
.container .text-center{ margin-top:2%; }
</style>

<style>
.scale{top: -18px;
position: relative; clear:both; width:100%;}
.scale span 
{
position: absolute;
height: 5px;
border-left: 1px solid #999;
font-size: 0;
}
.scale ins 
{
color: #333;
font-size: 12px;
text-decoration: none;
position: absolute;
left: 0;
top: 10px;
line-height: 1;
}
</style>
  <body>
	
    <?php include('menu.php'); ?>
    
    <div id="breadcrumb">
		<div class="container">	
			<div class="breadcrumb">							
				<li><a href="index.php">Home</a></li>
				<li>Personality Test Result</li>			
			</div>		
		</div>	
	</div>
    
    <!--/#main-slider-->
    	 
         
         <div class="container" style="color:#000; font-weight:bold;">
        <h1 style="color:#900; font-weight:bold;"> Congratulation's !!! You Have Successfully completed your  Personality Test </h1>
        <br/>
        <h1 style="color:#00F;">
        Based on your responses, an in-depth analysis report has been generated by experts , and it is represented with the following 4 traits <br/>
        </h1>
        <br/>
        <br/>
         
         
		<div class="container" style="color:#000;">
             <div class="row">
             <div class="col-lg-3">
			 <?php 
			  // echo '<pre>';print_r($res);echo '</pre>';
               $i=1;
			   foreach($res as $k1=>$val)
			   {
                    if($k1=='E') $meaning =  'Extroversion';
                    if($k1=='A') $meaning =  'Agreeableness';
                    if($k1=='C') $meaning =  'Conscientiousness';
                    if($k1=='N') $meaning =  'Neuroticism';
                    if($k1=='O') $meaning =  'Openness to Experience';
                    echo $k1.'('.$meaning.')'.'='.$val.'<br/><br/>';
					echo '<div class="progress-wrap">';
					echo '<div class="progress">';
					//echo '<div class="progress-bar color'.$i.' role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="40" style="width: '.$val.'%">';
					//echo '<span class="bar-width">'.$val.'</span>';
					?>
                    <div class="progress-bar color<?=$i;?>" role="progressbar" aria-valuenow="<?=$val*2.5;?>" aria-valuemin="0" aria-valuemax="100" style="width:<?=$val*2.5;?>%"><?=$val?> 
                    <?php
					echo '</div>';
					echo '</div>';
					?>
                    <div class="scale">
                    <span style="left: 0%"> <ins style="margin-left: -4px;">0</ins></span>
                    <span style="left: 25%"> <ins style="margin-left: -4px;">10</ins></span>
                    <span style="left: 50%"><ins style="margin-left: -2.5px;">20</ins></span>
                    <span style="left: 75%"><ins style="margin-left: -2.5px;">30</ins></span>
                    <span style="left: 100%"><ins style="margin-left: -2.5px;">40</ins></span>
                    </div>
                    <?php
					echo '</div>';
                    $i++;
			   }
			   ?>
               </div>
               
              
               
               <div class="col-lg-7">
               <div class="well" style="background-color:#e6e6e6;">
                   <p> <b style="color:#2d7da4;"> Extroversion (E) </b> is the personality trait of seeking fulfillment from sources outside the self or in community.
                   High scorers tend to be very social while low scorers prefer to work on their projects alone. </p>
                   <p> <b style="color:#6aa42f;">  Agreeableness (A) </b> reflects much individuals adjust their behavior to suit others.
                   High Scores are typically polite and like people. Low scorers tend to 'tell it like is.'
                   </p>
                   <p> <b style="color:#ffcc33;"> Conscientiousness(C)</b> is the personality trait of being honest and hardworking.
                   High scores tend to follow rules and prefer clean homes. Low scorers may be messy and cheat others.
                   </p>
                   <p>
                       <b style="color:#db3615;">  Neuroticism(N) </b> is the personality trait of being emotional
                   </p>
                   <p>
                       <b style="color:#38cbcb;"> Openness to Experience (O) </b> is the personality trait of seeking new experience and intellectual pursuits.
                       High Scores may dream a lot. Low scores may be very down to earth.
                   </p>
               </div>
               </div>
               
                <br/> <br/>
                <div class="col-lg-12">
                <br/><br/>
                <h1 style="color:#900; font-weight:bold;">To Get Complete Career Choice Report</h1>
                <a class="btn btn-large" style="background-color:#03C; color:#FFF;" href="http://www.careerprism.in/invoice">
                <b>Career Report</b>
                </a>
                <br/>
                </div>
               
               </div>
		</div>
        
        <br/><br/><br/>
        
   <?php
   include('footer.php');
   ?>
	
	
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	<script src="<?php echo base_url(); ?>assets/template/js/jquery-2.1.1.min.js"></script>	
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="<?php echo base_url(); ?>assets/template/js/bootstrap.min.js"></script>
	<script src="<?php echo base_url(); ?>assets/template/js/jquery.prettyPhoto.js"></script>
    <script src="<?php echo base_url(); ?>assets/template/js/jquery.isotope.min.js"></script>  
	<script src="<?php echo base_url(); ?>assets/template/js/wow.min.js"></script>
	<script src="<?php echo base_url(); ?>assets/template/js/functions.js"></script>
	
</body>
</html>