<?php
$config['personality_test_questions'] =

       array(
          '1' => array( 'question'  =>  'In decision making,i remain with my objectives', 'trait' => 'E', 'calculation' => '+20'),
		  '2' => array( 'question'  =>  'My feelings come front of my decisions', 'trait' => 'A', 'calculation' => '-14'),
		  '3' => array( 'question'  =>  'I like to make decisions quickly and move on to next', 'trait' => 'C', 'calculation' => '+14'),
		  '4' => array( 'question'  =>  'I will take decsions but still think about other options', 'trait' => 'N', 'calculation' => '-38'),
		  '5' => array( 'question'  =>  'I like to work on things i already know and comfortable', 'trait' => 'O', 'calculation' => '+8'),
		  '6' => array( 'question'  =>  'I am logical but i do have heart,too', 'trait' => 'E', 'calculation' => '-'),
		  '7' => array( 'question'  =>  'I am consistent and systematic', 'trait' => 'A', 'calculation' => '+'),
		  '8' => array( 'question'  =>  'I am a practical,hands on worker', 'trait' => 'C', 'calculation' => '-'),
		  '9' => array( 'question'  =>  'I will not be paied for ideas, i just work', 'trait' => 'N', 'calculation' => '+'),
		  '10' => array( 'question'  => 'I am a detail person', 'trait' => 'O', 'calculation' => '-'),
		  '11' => array( 'question' =>  'I dont stress out for small issues', 'trait' => 'E', 'calculation' => '+'),
		  '12' => array( 'question' => 'I like to watch and listen in social meetings', 'trait' => 'A', 'calculation' => '-'),
		  '13' => array( 'question' => 'I learn by seeing pictures and diagrams', 'trait' => 'C', 'calculation' => '+'),
		  '14' => array( 'question' => 'I prefer to learn by doing my own experiments', 'trait' => 'N', 'calculation' => '-'),
		  '15' => array( 'question' => 'I like to read the instructions first before using anything', 'trait' => 'O', 'calculation' => '+'),
		  '16' => array( 'question' => 'It will be difficult for me to do job without training', 'trait' => 'E', 'calculation' => '-'),
		  '17' => array( 'question' => 'I can never convince people', 'trait' => 'A', 'calculation' => '+'),
		  '18' => array( 'question' => 'I struggle describing complicated issues', 'trait' => 'C', 'calculation' => '-'),
		  '19' => array( 'question' => 'I am comfortable while writing clear instructions', 'trait' => 'N', 'calculation' => '+'),
		  '20' => array( 'question' => 'I feel difficulty in computing numbers in my head', 'trait' => 'O', 'calculation' => '-'),
		  '21' => array( 'question' => 'I accept things in which ever way they are.', 'trait' => 'E', 'calculation' => '+'),
		  '22' => array( 'question' => 'I like arts and paintings', 'trait' => 'A', 'calculation' => '-'),
		  '23' => array( 'question' => 'I can visualize things and make it real', 'trait' => 'C', 'calculation' => '+'),
		  '24' => array( 'question' => 'I would love to take risks in life', 'trait' => 'N', 'calculation' => '-'),
		  '25' => array( 'question' => 'I like filmstars and their dressings', 'trait' => 'O', 'calculation' => '+'),
		  '26' => array( 'question' => 'I dont like too much thinking while decision making','trait' => 'E', 'calculation' => '-'),
		  '27' => array( 'question' => 'My decsion will be shaped by others advice', 'trait' => 'A', 'calculation' => '+'),
		  '28' => array( 'question' => 'It is very difficult to take my own decision', 'trait' => 'C', 'calculation' => '-'),
		  '29' => array( 'question' => 'I would like to develop new,innovative systems','trait' => 'N', 'calculation' => '-'),
		  '30' => array( 'question' => 'I prefer improving old and existing methods','trait' => 'O', 'calculation' => '-'),
		  '31' => array( 'question' => 'I dont have logics,i just work','trait' => 'E', 'calculation' => '+'),
		  '32' => array( 'question' => 'I am friendly and sensitive','trait' => 'A', 'calculation' => '-'),
		  '33' => array( 'question' => 'I am an idea person','trait' => 'C', 'calculation' => '+'),
		  '34' => array( 'question' => 'I am a hands on worker with occasional ideas', 'trait' => 'N', 'calculation' => '-'),
		  '35' => array( 'question' => 'I dont focus in anything is just complete the job', 'trait' => 'O', 'calculation' => '+'),
		  '36' => array( 'question' => 'I would like to go with the flow,sometimes details are important', 'trait' => 'E', 'calculation' => '-'),
		  '37' => array( 'question' => 'I dont like to know about what other people are doing', 'trait' => 'A', 'calculation' => '+'),
		  '38' => array( 'question' => 'Learning is a struggle for me', 'trait' => 'C', 'calculation' => '-'),
		  '39' => array( 'question' => 'I like classes with visual and hands on practice', 'trait' => 'N', 'calculation' => '-'),
		  '40' => array( 'question' => 'I can figure the things without directions', 'trait' => 'O', 'calculation' => '+'),
		  '41' => array( 'question' => 'I convince others that i am right', 'trait' => 'E', 'calculation' => '+'),
		  '42' => array( 'question' => 'I can easily describe complex matters verbally', 'trait' => 'A', 'calculation' => '+'),
		  '43' => array( 'question' => 'I question the reason why things are the way they are', 'trait' => 'C', 'calculation' => '+'),
		  '44' => array( 'question' => 'I get irritated easily', 'trait' => 'N', 'calculation' => '-'),
		  '45' => array( 'question' => 'I am uncomfortable questionioning the reasons', 'trait' => 'O', 'calculation' => '+'),
		  '46' => array( 'question' => 'I can compute numerical values easily', 'trait' => 'E', 'calculation' => '-'),
		  '47' => array( 'question' => 'Being creative and artistic is highly respectable', 'trait' => 'A', 'calculation' => '+'),
		  '48' => array( 'question' => 'Designing with perfections make sense', 'trait' => 'C', 'calculation' => '+'),
		  '49' => array( 'question' => 'Better take calculated risks only', 'trait' => 'N', 'calculation' => '-'),
		  '50' => array( 'question' => 'I am always confused with the things i am doing', 'trait' => 'O', 'calculation' => '+')
          );

?>